AWSTemplateFormatVersion: "2010-09-09"
Description: "This stack is to generate an EC2 instance where it's accessible using SSM"
Parameters:
  AvailabilityZone:
    Type: String
    Default: ap-southeast-2a

Resources:
  containerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-sg
      GroupDescription: Security group for ec2-instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  ec2CfnInstance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-09a5c873bc79530d9 # ubuntu server 22.04 LTS (64-bit x86)
      InstanceInitiatedShutdownBehavior: terminate
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroupIds:
        - !GetAtt containerSecurityGroup.GroupId
      IamInstanceProfile: !Ref ec2SSMInstanceProfile

  ec2SSMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy # CloudWatchAgentServerPolicy
  
  ec2SSMInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ec2SSMRole

Outputs:
  ec2InstanceId:
    Description: EC2 Instance ID generated from this stack
    Value: !Ref ec2CfnInstance

  ec2InstanceDNS:
    Description: EC2 Instance DNS generated from this stack
    Value: !GetAtt ec2CfnInstance.PublicDnsName

  ec2InstancePublicIP:
    Description: EC2 Instance Public IP generated from this stack
    Value: !GetAtt ec2CfnInstance.PublicIp

  ssmawsclicommand:
    Description: The launch command for awscli using aws ssm
    Value: !Join ['', ['aws ssm start-session --target ', !Ref ec2CfnInstance]]